# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import gfs_pb2 as gfs__pb2

GRPC_GENERATED_VERSION = '1.81.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in gfs_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class MasterServiceStub:
    """MASTER SERVICE
    The Master is responsible for metadata management.
    Clients contact the Master to discover where data is stored.
    Chunkservers contact the Master to register themselves and send heartbeats.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.RegisterChunkserver = channel.unary_unary(
                '/gfs.MasterService/RegisterChunkserver',
                request_serializer=gfs__pb2.RegisterRequest.SerializeToString,
                response_deserializer=gfs__pb2.RegisterReply.FromString,
                _registered_method=True)
        self.Heartbeat = channel.unary_unary(
                '/gfs.MasterService/Heartbeat',
                request_serializer=gfs__pb2.HeartbeatRequest.SerializeToString,
                response_deserializer=gfs__pb2.HeartbeatReply.FromString,
                _registered_method=True)
        self.CreateFile = channel.unary_unary(
                '/gfs.MasterService/CreateFile',
                request_serializer=gfs__pb2.CreateFileRequest.SerializeToString,
                response_deserializer=gfs__pb2.CreateFileReply.FromString,
                _registered_method=True)
        self.GetChunkLocations = channel.unary_unary(
                '/gfs.MasterService/GetChunkLocations',
                request_serializer=gfs__pb2.ChunkLocationsRequest.SerializeToString,
                response_deserializer=gfs__pb2.ChunkLocationsReply.FromString,
                _registered_method=True)
        self.DeleteFile = channel.unary_unary(
                '/gfs.MasterService/DeleteFile',
                request_serializer=gfs__pb2.DeleteFileRequest.SerializeToString,
                response_deserializer=gfs__pb2.DeleteFileReply.FromString,
                _registered_method=True)


class MasterServiceServicer:
    """MASTER SERVICE
    The Master is responsible for metadata management.
    Clients contact the Master to discover where data is stored.
    Chunkservers contact the Master to register themselves and send heartbeats.

    """

    def RegisterChunkserver(self, request, context):
        """Called once when a Chunkserver starts. Registers the server with the Master so it can be used for storage.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Heartbeat(self, request, context):
        """Sent periodically by every Chunkserver.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateFile(self, request, context):
        """Client requests creation of a new file. The Master allocates the first chunk and selects initial replica locations.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetChunkLocations(self, request, context):
        """Client wants to access a specific chunk of a file. The Master returns chunk ID and addresses of Chunkservers storing that chunk
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteFile(self, request, context):
        """Removes a file from the namespace. Actual chunk garbage collection can happen later.)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_MasterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'RegisterChunkserver': grpc.unary_unary_rpc_method_handler(
                    servicer.RegisterChunkserver,
                    request_deserializer=gfs__pb2.RegisterRequest.FromString,
                    response_serializer=gfs__pb2.RegisterReply.SerializeToString,
            ),
            'Heartbeat': grpc.unary_unary_rpc_method_handler(
                    servicer.Heartbeat,
                    request_deserializer=gfs__pb2.HeartbeatRequest.FromString,
                    response_serializer=gfs__pb2.HeartbeatReply.SerializeToString,
            ),
            'CreateFile': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateFile,
                    request_deserializer=gfs__pb2.CreateFileRequest.FromString,
                    response_serializer=gfs__pb2.CreateFileReply.SerializeToString,
            ),
            'GetChunkLocations': grpc.unary_unary_rpc_method_handler(
                    servicer.GetChunkLocations,
                    request_deserializer=gfs__pb2.ChunkLocationsRequest.FromString,
                    response_serializer=gfs__pb2.ChunkLocationsReply.SerializeToString,
            ),
            'DeleteFile': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteFile,
                    request_deserializer=gfs__pb2.DeleteFileRequest.FromString,
                    response_serializer=gfs__pb2.DeleteFileReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gfs.MasterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gfs.MasterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class MasterService:
    """MASTER SERVICE
    The Master is responsible for metadata management.
    Clients contact the Master to discover where data is stored.
    Chunkservers contact the Master to register themselves and send heartbeats.

    """

    @staticmethod
    def RegisterChunkserver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.MasterService/RegisterChunkserver',
            gfs__pb2.RegisterRequest.SerializeToString,
            gfs__pb2.RegisterReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Heartbeat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.MasterService/Heartbeat',
            gfs__pb2.HeartbeatRequest.SerializeToString,
            gfs__pb2.HeartbeatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.MasterService/CreateFile',
            gfs__pb2.CreateFileRequest.SerializeToString,
            gfs__pb2.CreateFileReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetChunkLocations(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.MasterService/GetChunkLocations',
            gfs__pb2.ChunkLocationsRequest.SerializeToString,
            gfs__pb2.ChunkLocationsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.MasterService/DeleteFile',
            gfs__pb2.DeleteFileRequest.SerializeToString,
            gfs__pb2.DeleteFileReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class ChunkServiceStub:
    """CHUNKSERVER SERVICE
    Chunkservers store raw chunk data.
    Clients directly call these RPCs after obtaining chunk locations from the Master.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReadChunk = channel.unary_unary(
                '/gfs.ChunkService/ReadChunk',
                request_serializer=gfs__pb2.ReadChunkRequest.SerializeToString,
                response_deserializer=gfs__pb2.ReadChunkReply.FromString,
                _registered_method=True)
        self.WriteChunk = channel.unary_unary(
                '/gfs.ChunkService/WriteChunk',
                request_serializer=gfs__pb2.WriteChunkRequest.SerializeToString,
                response_deserializer=gfs__pb2.WriteChunkReply.FromString,
                _registered_method=True)
        self.AppendRecord = channel.unary_unary(
                '/gfs.ChunkService/AppendRecord',
                request_serializer=gfs__pb2.AppendRequest.SerializeToString,
                response_deserializer=gfs__pb2.AppendReply.FromString,
                _registered_method=True)
        self.ReplicateChunk = channel.unary_unary(
                '/gfs.ChunkService/ReplicateChunk',
                request_serializer=gfs__pb2.ReplicateRequest.SerializeToString,
                response_deserializer=gfs__pb2.ReplicateReply.FromString,
                _registered_method=True)


class ChunkServiceServicer:
    """CHUNKSERVER SERVICE
    Chunkservers store raw chunk data.
    Clients directly call these RPCs after obtaining chunk locations from the Master.

    """

    def ReadChunk(self, request, context):
        """Read bytes from an existing chunk.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def WriteChunk(self, request, context):
        """Write bytes into an existing chunk.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AppendRecord(self, request, context):
        """Append a record to the end of a chunk. The Chunkserver decides the final offset.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ReplicateChunk(self, request, context):
        """Used by the Master to create replicas. The receiving Chunkserver pulls the chunk from source_address.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChunkServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReadChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.ReadChunk,
                    request_deserializer=gfs__pb2.ReadChunkRequest.FromString,
                    response_serializer=gfs__pb2.ReadChunkReply.SerializeToString,
            ),
            'WriteChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.WriteChunk,
                    request_deserializer=gfs__pb2.WriteChunkRequest.FromString,
                    response_serializer=gfs__pb2.WriteChunkReply.SerializeToString,
            ),
            'AppendRecord': grpc.unary_unary_rpc_method_handler(
                    servicer.AppendRecord,
                    request_deserializer=gfs__pb2.AppendRequest.FromString,
                    response_serializer=gfs__pb2.AppendReply.SerializeToString,
            ),
            'ReplicateChunk': grpc.unary_unary_rpc_method_handler(
                    servicer.ReplicateChunk,
                    request_deserializer=gfs__pb2.ReplicateRequest.FromString,
                    response_serializer=gfs__pb2.ReplicateReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'gfs.ChunkService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('gfs.ChunkService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ChunkService:
    """CHUNKSERVER SERVICE
    Chunkservers store raw chunk data.
    Clients directly call these RPCs after obtaining chunk locations from the Master.

    """

    @staticmethod
    def ReadChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.ChunkService/ReadChunk',
            gfs__pb2.ReadChunkRequest.SerializeToString,
            gfs__pb2.ReadChunkReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def WriteChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.ChunkService/WriteChunk',
            gfs__pb2.WriteChunkRequest.SerializeToString,
            gfs__pb2.WriteChunkReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AppendRecord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.ChunkService/AppendRecord',
            gfs__pb2.AppendRequest.SerializeToString,
            gfs__pb2.AppendReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ReplicateChunk(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/gfs.ChunkService/ReplicateChunk',
            gfs__pb2.ReplicateRequest.SerializeToString,
            gfs__pb2.ReplicateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
